### ISSUE TITLE
求助！！！

### ISSUE THREAD

**Issue by zzsimonss** [pjialin/w-forum#1]
您好，我在 为我 上订阅了您的课程，但是发现您停止更新了。我还想继续学习接下来的课程，能否把完整的代码发给我？我自学一下。
谢谢！
我的邮箱 zzhangshuaii@gmail.com

**Comment by pjialin** [comment]
抱歉，才看到你的消息，确实出了一些状况暂时没有更新了，稍后我会将源代码发到你邮箱，感谢支持！

**Comment by pjialin** [comment]
> 您好，我在 为我 上订阅了您的课程，但是发现您停止更新了。我还想继续学习接下来的课程，能否把完整的代码发给我？我自学一下。
> 谢谢！
> 我的邮箱 [zzhangshuaii@gmail.com](mailto:zzhangshuaii@gmail.com)

抱歉，才看到你的消息，确实出了一些状况暂时没有更新了，稍后我会将源代码发到你邮箱，感谢支持！
